---
version: '3.2'
services:
  nginx:
    image: nginx:1.17.8
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx/conf.d
    networks:
      - moodledocker_frontend
      - wordpressdocker_frontend
      - cryptpaddocker_frontend
    restart: always


  dockergen:
    image: jwilder/docker-gen
    command:
        - -notify-sighup
        - nginx
        - -watch
        - /etc/docker-gen/templates/nginx.tmpl
        - /etc/nginx/conf.d/default.conf
    container_name: nginx-docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - nginx-config:/etc/nginx/conf.d
    networks:
      - moodledocker_frontend
      - wordpressdocker_frontend
      - cryptpaddocker_frontend
    restart: always

volumes:
  nginx-config: {}

networks:
  moodledocker_frontend:
    external: true
  wordpressdocker_frontend:
    external: true
  cryptpaddocker_frontend:
    external: true
